Vagrant.configure("2") do |config|

  #  Select any box created for VMware that is compatible with
  #    the ovftool.  To get maximum compatiblity You should download
  #    and install the latest version for your OS.
  #    https://www.vmware.com/support/developer/ovf/
  #
  #    If your box is stuck at "Powered On", then most likely
  #    the system doesn't have the vmware tools installed.
  #
  # Here are some of the MANY box examples....
  config.vm.box = 'hashicorp/precise64'
  #config.vm.box = 'steveant/CentOS-7.0-1406-Minimal-x64'
  #config.vm.box = 'geerlingguy/ubuntu1604'
  #config.vm.box = 'laravel/homestead'
  #config.vm.box = 'bento/ubuntu-14.04'
  #config.vm.box = 'generic/centos7'
  #config.vm.box = 'generic/fedora26'
  #config.vm.box = 'generic/alpine36'


  #  Synced folders supports type rsync and NFS.
  config.vm.synced_folder('.', '/Vagrantfiles', type: 'rsync')

  #
  #  Provider (esxi) settings
  #
  config.vm.provider :vmware_esxi do |esxi|

    #  REQUIRED!  ESXi hostname/IP
    #    You MUST specify a esxi_hostname or IP, uless you
    #    were lucky enough to name your esxi host "esxi".  :-)
    esxi.esxi_hostname = "esxi"

    #  ESXi username
    #    Default is "root".
    esxi.esxi_username = "root"

    #
    #  IMPORTANT!  ESXi password.
    #  *** NOTES about esxi_password & ssh keys!! ***
    #
    #    1)  esxi.esxi_password = "my_esxi_password"
    #        Enter your esxi passowrd in clear text here...
    #
    #    2)  "key:"  or  ""  or "key:~/.ssh/some_ssh_private_key"
    #        Use ssh keys.  The default is to use the system private keys,
    #        or you specify a custom private key after the colon ":".
    #
    #        From your command line, you should be able to run
    #        following command without an error and be able to get to
    #        the esxi command prompt.
    #
    #            $ ssh root@ESXi_IP_ADDRESS
    #
    #        The ssh connections to esxi will try the ssh private
    #        keys.  However the ovftool does NOT!  To make
    #        vagrant fully password-less, you will need to use other
    #        options. (set the passord, use "env:" or "file:")
    #
    #    3) "prompt:"
    #       This will prompt you for the esxi password each time you
    #       run a vagrant command.
    #
    #    4) "file:"  or  "file:my_secret_file"
    #       This will read a plain text file containing the esxi
    #       password.   The default filename is ~/.esxi_password, or
    #       you can specify any filename after the colon ":".
    #
    #    5) "env:"  or "env:my_secret_env_var"
    #        This will read the esxi password via a environment
    #        variable.  The default is $esxi_password, but you can
    #        specify any environment variable after the colon ":".
    #
    #            $ export esxi_password="my_secret_password"
    #
    #
    #  IMPORTANT!  Set the ESXi password.
    esxi.esxi_password = "prompt:"

    #  ESXi ssh keys.   (This will be depreciated!!!)
    #    The Default is to use system default ssh keys, However
    #    you can specify an array of keys here...
    #
    #   ***  Depreciated, use esxi_password = "key:" instead. ***
    #esxi.esxi_private_keys = []

    #  SSH port.
    #    Default port 22
    #esxi.esxi_hostport = 22

    #  HIGHLY RECOMMENDED!  Virtual Network
    #    You should specify a Virtual Network!
    #    The default is to use the first found!
    #    You can specify up to 4 virtual networks using an array format.
    #esxi.virtual_network = "vmnet_example"
    #esxi.virtual_network = ["vmnet1","vmnet2","vmnet3","vmnet4"]

    #  OPTIONAL.  Specify a Disk Store
    #    The Default is to use the least used Disk Store.
    #esxi.vm_disk_store = "DS_001"

    #  OPTIONAL.  Guest VM name to be created/used.
    #    The Default will be automatically generated
    #    and will be based on the vmname_prefix,
    #    hostname, username, path...
    #esxi.vmname = "Custom-Guest-VM_Name"

    #  OPTIONAL.  When automatically naming VMs, use
    #    this prifix.
    #esxi.vmname_prefix = "V-"

    #  OPTIONAL.  Memory size override
    #    The default is to use the memory size specified in the
    #    vmx file, however you can specify a new value here.
    #esxi.memsize = "2048"

    #  OPTIONAL.  Virtual CPUs override
    #    The default is to use the number of virt cpus specified
    #     in the vmx file, however you can specify a new value here.
    #esxi.numvcpus = "2"

    #  OPTIONAL.  Resource Pool
    #    The default is to create VMs in the "root".  You can
    #     specify a resource pool here to partition memory and
    #     cpu usage away from other systems on your esxi host.
    #     The resource pool must already exist and be configured.
    #     Vagrant will NOT create it for you.
    #esxi.resource_pool = "/Vagrant"

    #  DANGEROUS!  Allow Overwrite
    #    Set this to 'True' will overwrite existing VMs (with the same name)
    #    when you run vagrant up.   ie,  if the vmname already exists,
    #    it will be destroyed, then over written...  This is helpful
    #    if you have a VM that became an orphan (vagrant lost association).
    #    This will also overwrite your box when using vagrant package.
    #esxi.allow_overwrite = 'True'

  end
end
